# Ackowldedgements {-}

I would like to express my heartfelt gratitude to my supervisor, Sebastian Funk, and my co-supervisors, Anne Cori, and Edwin van Leeuwen, as well as my advisory committee, Sam Abbott and Johannes Bracher, for their unwavering support and guidance.

Sebastian, thank you for giving me great freedom to explore and find my own way while providing exceptional guidance and advice whenever I needed it. Thank you for your friendship, and for all your kindness, patience and support.

Anne, your kind and persistent encouragement, as well as your clear and pointed suggestions have been invaluable. Thank you for being just the right amount of impatient and pragmatic and for making sure things got done in the kindest way possible. 

Edwin, thank you for your warmth, your humour, your pointed questions, and insights, and all your support. It was a true pleasure to work with you and have you as a supervisor. 

Sam, you were one of the main reasons I started this PhD. Thank you for enduring my occasional less-than-perfect PR and for teaching me how to do better. Thank you for all the countless hours you have spent both on scoringutils and on relentlessly supporting me with my other projects. Acts speak louder than words, and your acts have spoken very loudly. Thank you for the truly exceptional mentorship and friendship you have shown me. 

Johannes, your insights on forecast evaluation have been invaluable and have made this work much better than it would have been without you. Thank you for the countless discussions on scoring rules, for your kindness, and for being always there to ensure that all things go their proper way.

Thank you to my friends and family who have supported me throughout this time. 
