# Comparing human and model-based forecasts of COVID-19 in Germany and Poland
\label{sec:GermanyPoland}

This chapter investigates what human judgement can contribute to infectious disease forecasting, applying the foundational concepts that were covered in Chapter \ref{sec:scoringutils}. The work in this chapter was motivated by the need to produce timely and useful forecasts of COVID-19. In October 2020 the German and Polish COVID0-19 Forecast Hub \citep{bracherPreregisteredShorttermForecasting2021} launched, eliciting forecasts to help inform public health decision making in Germany and Poland. Previous submissions from our working group to the US COVID-19 Forecast Hub \citep{cramerEvaluationIndividualEnsemble2022} had proved cumbersome and it was not clear what the added benefit of mathematical modelling over human judgement alone was. We therefore developed an open source application, `crowdforecastr` \citep{crowdforecastr}, which would allow humans to submit direct forecasts of cases and deaths in Germany and Poland. These forecasts were collected every week, aggregated and submitted to the German and Polish Forecast Hub. In order to investigate a better understanding of what mathematical modelling may add to human judgement alone, we submitted these forecasts alongside two mathematical models with minimal tuning. In an additional analyses, we further explore how adding different forecasts affects the quality of an ensemble of forecasts. This analysis was motivated by the desire to better understand what kinds of forecasts may contribute to public health decision making, and whether even imperfect forecast models can contribute usefully. 

The study was limited both by resource constraints as well as the time that was available to develop the `crowdforecastr` platform, obtain ethics approval, conduct outreach, and the need to submit the first forecasts within 6 weeks of starting this PhD. The study should therefore better be understood as a case study that explores a variety of questions related to the interplay of human judgement and mathematical modelling, rather than an attempt to provide definitive conclusions. 




\clearpage


\includepdf[pages=-]{papers/Research Paper Cover Sheet-18 Paper 2.docx.pdf}

\includepdf[pages=-]{papers/Paper-2-Forecasts-Germany-Poland.pdf}
\includepdf[pages=-]{papers/Paper-2-SI.pdf}
