# Transformation of forecasts for evaluating predictive performance in an epidemiological context
\label{sec:LogTransformation}

Chapter \ref{sec:GermanyPoland} revealed a few shortcomings of the weighted interval score at it is commonly applied in epidemiology. We saw that average scores were dominated by outliers, and overall scores scaled with incidences. This made it difficult to compare forecasts across time and location, and in particular across forecast targets. More importantly, there is a tension when evaluating forecasts on the absolute distance between forecast and observation, while the underlying process we try to model is exponential in nature. It might therefore be more appropriate to evaluate forecasts of infectious disease based on how well they capture the exponential growth rate of a disease process. This could provide a more meaningful signal about which forecasters to trust in the future, as it more closely represents the actual modelling task one has to solve in order to create an accurate representation of the spread of the infectious disease. 

Different scores emphasise different kinds of errors differently. For example, in Chapter \ref{sec:GermanyPoland}, the WIS penalised forecasts strongly that overshot after missing a peak. It did, however, penalise models only very lightly if they were too late to predict an increase in numbers while incidences were still low. Arguably, this kind of early warning is something that policy makers would care about, but which is neglected in current evaluations. Forecast evaluations play an important role not only as a signal to modellers who aim to improve their models. They also help decision makers select which models should inform their policies in the future. If the score does not accurately reflect what policy makers care about in a good forecast, then policy makers may not pick the best model to guide their decisions. 

Chapter \@ref(sec:LogTransformation) explores ways in which the forecast evaluation can be aligned more closely with what forecast consumers actually care about. One possible solution is to transform forecasts and observations before applying the WIS. We propose and analyse the natural logarithm as a transformation that is particularly attractive in an epidemiological context, but there are many more possible transformations. In particular, the idea of transforming forecasts opens up the possibility of creating composite scores, in which a score is constructed as a linear combination of scores obtained after various different transformation. This could, in the future, enable policy makers to create their own custom scores which exactly reflect what they care about. 

\clearpage


\includepdf[pages=-]{papers/Research Paper Cover Sheet-18 Paper 3.docx.pdf}

\includepdf[pages=-]{papers/Paper-3-LogTransformation.pdf}
\includepdf[pages=-]{papers/Paper-3-LogTransformation-SI.pdf}





