# Human Judgement Forecasting of COVID-19 in the UK
\label{sec:UKforecastingChallenge}

The crowd forecasts submitted to the German and Polish Forecast Hub described in Chapter \ref{sec:GermanyPoland} formed part of an acute COVID-19 response effort and therefore exhibited a few shortcomings that the study presented in this chapter aims to address. In particular, the study in Germany and Poland suffered from a low number of participants, both in terms of the crowd forecast as well as the number of model-based predictions submitted to the Forecast Hub. This makes it difficult to generalise findings. Forecasts were also only evaluated on the natural scale with all the shortcomings discussed in Chapter \ref{sec:LogTransformation}. 

This chapter describes a follow-up study conducted in the UK. In order to increase and diversify participation, we organised the study in the form of a public forecasting tournament, the "UK Crowd Forecasting Challenge". This allowed us to analyse whether findings from the initial study would hold in a different setting with a larger pool of participants. Forecasts were analysed both on the natural and on the log scale, providing a more complete picture of the predictive performance of human judgement forecasts. 

This chapter also extends the work in Chapter \ref{sec:GermanyPoland} by exploring a novel way to combine human judgement and mathematical modelling as proposed in the original work. Instead of asking forecasters to predict case and death incidences directly, we elicited forecasts of the effective reproduction number $R_t$ which then got mapped to cases and deaths using an epidemiological model. The motivation behind this idea was twofold. On the one hand this might be a possibility to improve forecasts by providing a means to harness the respective strengths of human judgement and mathematical modelling. On the other hand, combining human judgement and mathematical modelling might be a way to make human judgement forecasting more scalable by reducing the cognitive load and the number of forecasts an individual needs to provide. 


\clearpage

\includepdf[pages=-]{papers/Research Paper Cover Sheet-18 Paper 4.docx.pdf}

\includepdf[pages=-]{papers/Paper-4-UK-challenge.pdf}
\includepdf[pages=-]{papers/Paper-4-SI.pdf}
